import { Problem } from '../types'

export const generateMath3Problems = (): Problem[] => {
  return [
    // Easy Problems
    {
      id: '61',
      courseId: 'math3',
      course: {} as any,
      title: 'Quadratic Formula',
      content: 'Solve: x² - 5x + 6 = 0\nEnter the larger root.',
      solution: '3',
      difficulty: 'easy',
      topics: ['Quadratic Equations'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '62',
      courseId: 'math3',
      course: {} as any,
      title: 'Complex Numbers',
      content: 'Simplify: (3 + 4i)(2 - i)\nEnter the real part only.',
      solution: '10',
      difficulty: 'easy',
      topics: ['Complex Numbers'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '63',
      courseId: 'math3',
      course: {} as any,
      title: 'Logarithmic Equation',
      content: 'Solve: log₂(x) = 4\nEnter the value of x.',
      solution: '16',
      difficulty: 'easy',
      topics: ['Logarithms'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '64',
      courseId: 'math3',
      course: {} as any,
      title: 'Exponential Equation',
      content: 'Solve: 2^x = 16\nEnter the value of x.',
      solution: '4',
      difficulty: 'easy',
      topics: ['Exponential Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '65',
      courseId: 'math3',
      course: {} as any,
      title: 'Polynomial Degree',
      content: 'What is the degree of the polynomial 3x⁴ - 2x² + 5x - 1?',
      solution: '4',
      difficulty: 'easy',
      topics: ['Polynomials'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '66',
      courseId: 'math3',
      course: {} as any,
      title: 'Factoring Quadratic',
      content: 'Factor: x² + 7x + 12\nEnter the sum of the two factors.',
      solution: '7',
      difficulty: 'easy',
      topics: ['Factoring'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '67',
      courseId: 'math3',
      course: {} as any,
      title: 'Rational Expression',
      content: 'Simplify: (x² - 4)/(x - 2)\nEnter the coefficient of x in the result.',
      solution: '1',
      difficulty: 'easy',
      topics: ['Rational Expressions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '68',
      courseId: 'math3',
      course: {} as any,
      title: 'Function Evaluation',
      content: 'If f(x) = x² + 3x - 2, find f(2)\nEnter only the numerical value.',
      solution: '8',
      difficulty: 'easy',
      topics: ['Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '69',
      courseId: 'math3',
      course: {} as any,
      title: 'Absolute Value',
      content: 'Solve: |2x - 1| = 5\nEnter the larger value of x.',
      solution: '3',
      difficulty: 'easy',
      topics: ['Absolute Value'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '70',
      courseId: 'math3',
      course: {} as any,
      title: 'Inequality',
      content: 'Solve: 3x - 2 > 7\nEnter the smallest integer value of x.',
      solution: '4',
      difficulty: 'easy',
      topics: ['Inequalities'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Medium Problems
    {
      id: '71',
      courseId: 'math3',
      course: {} as any,
      title: 'Complex Quadratic',
      content: 'Solve: 2x² - 5x - 3 = 0\nEnter the larger root.',
      solution: '3',
      difficulty: 'medium',
      topics: ['Quadratic Equations'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '72',
      courseId: 'math3',
      course: {} as any,
      title: 'Complex Number Division',
      content: 'Simplify: (6 + 8i)/(2 + i)\nEnter the real part only.',
      solution: '4',
      difficulty: 'medium',
      topics: ['Complex Numbers'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '73',
      courseId: 'math3',
      course: {} as any,
      title: 'Logarithmic Properties',
      content: 'Simplify: log₃(27) + log₃(9)\nEnter the numerical value.',
      solution: '5',
      difficulty: 'medium',
      topics: ['Logarithms'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '74',
      courseId: 'math3',
      course: {} as any,
      title: 'Exponential Growth',
      content: 'If a population doubles every 3 years, what is the annual growth rate? Enter as a decimal.',
      solution: '0.26',
      difficulty: 'medium',
      topics: ['Exponential Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '75',
      courseId: 'math3',
      course: {} as any,
      title: 'Polynomial Division',
      content: 'Divide: (x³ - 8)/(x - 2)\nEnter the coefficient of x² in the result.',
      solution: '1',
      difficulty: 'medium',
      topics: ['Polynomials'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '76',
      courseId: 'math3',
      course: {} as any,
      title: 'Rational Function',
      content: 'Find the vertical asymptote of f(x) = (x + 2)/(x - 3)\nEnter the x-value.',
      solution: '3',
      difficulty: 'medium',
      topics: ['Rational Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '77',
      courseId: 'math3',
      course: {} as any,
      title: 'Function Composition',
      content: 'If f(x) = x² and g(x) = x + 1, find f(g(3))\nEnter only the numerical value.',
      solution: '16',
      difficulty: 'medium',
      topics: ['Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '78',
      courseId: 'math3',
      course: {} as any,
      title: 'Absolute Value Inequality',
      content: 'Solve: |3x - 2| < 7\nEnter the largest integer value of x.',
      solution: '2',
      difficulty: 'medium',
      topics: ['Absolute Value'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '79',
      courseId: 'math3',
      course: {} as any,
      title: 'Compound Inequality',
      content: 'Solve: -2 < 3x + 1 < 10\nEnter the largest integer value of x.',
      solution: '2',
      difficulty: 'medium',
      topics: ['Inequalities'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '80',
      courseId: 'math3',
      course: {} as any,
      title: 'Quadratic Inequality',
      content: 'Solve: x² - 4x + 3 > 0\nEnter the smallest integer value of x that satisfies the inequality.',
      solution: '4',
      difficulty: 'medium',
      topics: ['Quadratic Inequalities'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Hard Problems
    {
      id: '81',
      courseId: 'math3',
      course: {} as any,
      title: 'Complex Quadratic Formula',
      content: 'Solve: x² - 6x + 13 = 0\nEnter the real part of the solution.',
      solution: '3',
      difficulty: 'hard',
      topics: ['Quadratic Equations'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '82',
      courseId: 'math3',
      course: {} as any,
      title: 'Complex Number Powers',
      content: 'Simplify: (1 + i)⁴\nEnter the real part only.',
      solution: '-4',
      difficulty: 'hard',
      topics: ['Complex Numbers'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '83',
      courseId: 'math3',
      course: {} as any,
      title: 'Logarithmic Equation',
      content: 'Solve: log₅(x) + log₅(x + 2) = 1\nEnter the value of x.',
      solution: '3',
      difficulty: 'hard',
      topics: ['Logarithms'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '84',
      courseId: 'math3',
      course: {} as any,
      title: 'Exponential Equation',
      content: 'Solve: 3^(2x) = 27^(x-1)\nEnter the value of x.',
      solution: '3',
      difficulty: 'hard',
      topics: ['Exponential Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '85',
      courseId: 'math3',
      course: {} as any,
      title: 'Polynomial Roots',
      content: 'If x = 2 is a root of x³ - 3x² + 4x - 8 = 0, what is the sum of the other two roots?',
      solution: '1',
      difficulty: 'hard',
      topics: ['Polynomials'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '86',
      courseId: 'math3',
      course: {} as any,
      title: 'Rational Function Asymptotes',
      content: 'Find the horizontal asymptote of f(x) = (2x² + 3x)/(x² - 1)\nEnter the y-value.',
      solution: '2',
      difficulty: 'hard',
      topics: ['Rational Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '87',
      courseId: 'math3',
      course: {} as any,
      title: 'Function Domain',
      content: 'Find the domain of f(x) = √(x² - 4)\nEnter the smallest integer not in the domain.',
      solution: '-2',
      difficulty: 'hard',
      topics: ['Functions'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '88',
      courseId: 'math3',
      course: {} as any,
      title: 'Absolute Value Equation',
      content: 'Solve: |x² - 4| = |x - 2|\nEnter the largest value of x.',
      solution: '3',
      difficulty: 'hard',
      topics: ['Absolute Value'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '89',
      courseId: 'math3',
      course: {} as any,
      title: 'System of Inequalities',
      content: 'Solve the system:\nx + y > 3\n2x - y < 4\nEnter the smallest integer value of x that satisfies both inequalities.',
      solution: '2',
      difficulty: 'hard',
      topics: ['Inequalities'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '90',
      courseId: 'math3',
      course: {} as any,
      title: 'Quadratic System',
      content: 'Solve the system:\nx² + y² = 25\nx + y = 7\nEnter the larger value of x.',
      solution: '4',
      difficulty: 'hard',
      topics: ['Systems of Equations'],
      source: 'Algebra 2 Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]
}

export const generatePrecalcProblems = (): Problem[] => {
  return [
    // Easy Problems
    {
      id: '91',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Identity',
      content: 'What is sin(π/6)?',
      solution: '0.5',
      difficulty: 'easy',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '92',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Operations',
      content: 'Find the magnitude of vector v = <3, 4>',
      solution: '5',
      difficulty: 'easy',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '93',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Determinant',
      content: 'Find the determinant of:\n|2 3|\n|1 4|\nEnter the numerical value.',
      solution: '5',
      difficulty: 'easy',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '94',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Number Operations',
      content: 'Simplify: (2 + 3i)(1 - i)\nEnter the real part only.',
      solution: '5',
      difficulty: 'easy',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '95',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Function',
      content: 'What is cos(π/3)?',
      solution: '0.5',
      difficulty: 'easy',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '96',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Addition',
      content: 'Add vectors <2, 3> and <1, 4>\nEnter the x-component of the result.',
      solution: '3',
      difficulty: 'easy',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '97',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Addition',
      content: 'Add matrices:\n|1 2| + |3 1|\n|3 4|   |2 5|\nEnter the element in row 1, column 1.',
      solution: '4',
      difficulty: 'easy',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '98',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Conjugate',
      content: 'Find the conjugate of 3 + 4i\nEnter the real part.',
      solution: '3',
      difficulty: 'easy',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '99',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Function',
      content: 'What is tan(π/4)?',
      solution: '1',
      difficulty: 'easy',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '100',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Scalar Multiplication',
      content: 'Multiply vector <2, 3> by scalar 4\nEnter the x-component.',
      solution: '8',
      difficulty: 'easy',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Medium Problems
    {
      id: '101',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Identity',
      content: 'Simplify: sin²(x) + cos²(x)\nEnter the numerical value.',
      solution: '1',
      difficulty: 'medium',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '102',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Dot Product',
      content: 'Find the dot product of <2, 3> and <4, 1>',
      solution: '11',
      difficulty: 'medium',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '103',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Multiplication',
      content: 'Multiply:\n|1 2| |3 1|\n|3 4| |2 5|\nEnter the element in row 1, column 1.',
      solution: '7',
      difficulty: 'medium',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '104',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Number Division',
      content: 'Divide: (6 + 8i)/(2 + i)\nEnter the real part only.',
      solution: '4',
      difficulty: 'medium',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '105',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Equation',
      content: 'Solve: sin(x) = 0.5 in [0, π]\nEnter the value of x in radians.',
      solution: '0.52',
      difficulty: 'medium',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '106',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Cross Product',
      content: 'Find the cross product of <1, 0, 0> and <0, 1, 0>\nEnter the z-component.',
      solution: '1',
      difficulty: 'medium',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '107',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Inverse',
      content: 'Find the inverse of:\n|2 1|\n|1 3|\nEnter the element in row 1, column 1.',
      solution: '0.6',
      difficulty: 'medium',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '108',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Number Powers',
      content: 'Simplify: (1 + i)²\nEnter the real part only.',
      solution: '0',
      difficulty: 'medium',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '109',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Function',
      content: 'Find cos(2π/3)',
      solution: '-0.5',
      difficulty: 'medium',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '110',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Projection',
      content: 'Find the projection of <3, 4> onto <1, 0>\nEnter the x-component.',
      solution: '3',
      difficulty: 'medium',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Hard Problems
    {
      id: '111',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Identity',
      content: 'Prove: sin(2x) = 2sin(x)cos(x)\nIf x = π/6, what is sin(2x)?',
      solution: '0.87',
      difficulty: 'hard',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '112',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Analysis',
      content: 'Find the angle between vectors <1, 1> and <1, 0>\nEnter the angle in degrees.',
      solution: '45',
      difficulty: 'hard',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '113',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Eigenvalues',
      content: 'Find the eigenvalues of:\n|3 1|\n|1 3|\nEnter the larger eigenvalue.',
      solution: '4',
      difficulty: 'hard',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '114',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Number Roots',
      content: 'Find the square roots of -4\nEnter the real part of the root with positive imaginary part.',
      solution: '0',
      difficulty: 'hard',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '115',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Equation',
      content: 'Solve: 2sin²(x) - sin(x) - 1 = 0 in [0, 2π]\nEnter the smallest positive solution in radians.',
      solution: '0.52',
      difficulty: 'hard',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '116',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Space',
      content: 'Are vectors <1, 2, 3>, <2, 4, 6>, <1, 1, 1> linearly independent? Enter 1 for yes, 0 for no.',
      solution: '0',
      difficulty: 'hard',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '117',
      courseId: 'precalc',
      course: {} as any,
      title: 'Matrix Rank',
      content: 'Find the rank of:\n|1 2 3|\n|2 4 6|\n|1 1 1|\nEnter the numerical value.',
      solution: '2',
      difficulty: 'hard',
      topics: ['Matrices'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '118',
      courseId: 'precalc',
      course: {} as any,
      title: 'Complex Number DeMoivre',
      content: 'Find (1 + i)⁶ using DeMoivre\'s theorem\nEnter the real part only.',
      solution: '-8',
      difficulty: 'hard',
      topics: ['Complex Numbers'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '119',
      courseId: 'precalc',
      course: {} as any,
      title: 'Trigonometric Series',
      content: 'Find the sum: sin(π/6) + sin(π/3) + sin(π/2)\nEnter the numerical value.',
      solution: '2.37',
      difficulty: 'hard',
      topics: ['Trigonometry'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '120',
      courseId: 'precalc',
      course: {} as any,
      title: 'Vector Calculus',
      content: 'Find the derivative of r(t) = <t², t³, t> at t = 1\nEnter the x-component.',
      solution: '2',
      difficulty: 'hard',
      topics: ['Vectors'],
      source: 'Precalculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]
}

export const generateCalculusProblems = (): Problem[] => {
  return [
    // Easy Problems
    {
      id: '121',
      courseId: 'calculus',
      course: {} as any,
      title: 'Limit Problem',
      content: 'Find the limit: lim(x→2) (x² - 4)/(x - 2)',
      solution: '4',
      difficulty: 'easy',
      topics: ['Limits'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '122',
      courseId: 'calculus',
      course: {} as any,
      title: 'Derivative Problem',
      content: 'Find the derivative of f(x) = x³ + 2x² - 5x + 1 at x = 2',
      solution: '15',
      difficulty: 'easy',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '123',
      courseId: 'calculus',
      course: {} as any,
      title: 'Integration Problem',
      content: 'Find ∫(2x + 3)dx from 0 to 2',
      solution: '10',
      difficulty: 'easy',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '124',
      courseId: 'calculus',
      course: {} as any,
      title: 'Basic Limit',
      content: 'Find the limit: lim(x→3) (x² - 9)/(x - 3)',
      solution: '6',
      difficulty: 'easy',
      topics: ['Limits'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '125',
      courseId: 'calculus',
      course: {} as any,
      title: 'Simple Derivative',
      content: 'Find the derivative of f(x) = x² + 3x - 2',
      solution: '2x + 3',
      difficulty: 'easy',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '126',
      courseId: 'calculus',
      course: {} as any,
      title: 'Basic Integration',
      content: 'Find ∫x²dx',
      solution: 'x³/3 + C',
      difficulty: 'easy',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '127',
      courseId: 'calculus',
      course: {} as any,
      title: 'Limit at Infinity',
      content: 'Find the limit: lim(x→∞) (3x + 1)/(2x - 1)',
      solution: '1.5',
      difficulty: 'easy',
      topics: ['Limits'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '128',
      courseId: 'calculus',
      course: {} as any,
      title: 'Power Rule',
      content: 'Find the derivative of f(x) = x⁴',
      solution: '4x³',
      difficulty: 'easy',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '129',
      courseId: 'calculus',
      course: {} as any,
      title: 'Definite Integral',
      content: 'Find ∫(x + 1)dx from 0 to 3',
      solution: '7.5',
      difficulty: 'easy',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '130',
      courseId: 'calculus',
      course: {} as any,
      title: 'Continuity',
      content: 'Is f(x) = x² continuous at x = 2? Enter 1 for yes, 0 for no.',
      solution: '1',
      difficulty: 'easy',
      topics: ['Continuity'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Medium Problems
    {
      id: '131',
      courseId: 'calculus',
      course: {} as any,
      title: 'Chain Rule',
      content: 'Find the derivative of f(x) = (x² + 1)³',
      solution: '6x(x² + 1)²',
      difficulty: 'medium',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '132',
      courseId: 'calculus',
      course: {} as any,
      title: 'Product Rule',
      content: 'Find the derivative of f(x) = x²sin(x)',
      solution: '2xsin(x) + x²cos(x)',
      difficulty: 'medium',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '133',
      courseId: 'calculus',
      course: {} as any,
      title: 'Quotient Rule',
      content: 'Find the derivative of f(x) = x/(x + 1)',
      solution: '1/(x + 1)²',
      difficulty: 'medium',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '134',
      courseId: 'calculus',
      course: {} as any,
      title: 'Integration by Parts',
      content: 'Find ∫x·e^x dx',
      solution: 'xe^x - e^x + C',
      difficulty: 'medium',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '135',
      courseId: 'calculus',
      course: {} as any,
      title: 'Substitution',
      content: 'Find ∫2x·e^(x²)dx',
      solution: 'e^(x²) + C',
      difficulty: 'medium',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '136',
      courseId: 'calculus',
      course: {} as any,
      title: 'L\'Hôpital\'s Rule',
      content: 'Find the limit: lim(x→0) sin(x)/x',
      solution: '1',
      difficulty: 'medium',
      topics: ['Limits'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '137',
      courseId: 'calculus',
      course: {} as any,
      title: 'Critical Points',
      content: 'Find the critical points of f(x) = x³ - 3x² + 2',
      solution: '0, 2',
      difficulty: 'medium',
      topics: ['Applications'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '138',
      courseId: 'calculus',
      course: {} as any,
      title: 'Area Between Curves',
      content: 'Find the area between y = x² and y = x from x = 0 to x = 1',
      solution: '1/6',
      difficulty: 'medium',
      topics: ['Applications'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '139',
      courseId: 'calculus',
      course: {} as any,
      title: 'Volume of Revolution',
      content: 'Find the volume when y = x² is rotated around the x-axis from x = 0 to x = 2',
      solution: '32π/5',
      difficulty: 'medium',
      topics: ['Applications'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '140',
      courseId: 'calculus',
      course: {} as any,
      title: 'Related Rates',
      content: 'A circle\'s radius is increasing at 2 cm/s. When r = 5 cm, how fast is the area increasing?',
      solution: '20π',
      difficulty: 'medium',
      topics: ['Applications'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    // Hard Problems
    {
      id: '141',
      courseId: 'calculus',
      course: {} as any,
      title: 'Implicit Differentiation',
      content: 'Find dy/dx for x² + y² = 25',
      solution: '-x/y',
      difficulty: 'hard',
      topics: ['Derivatives'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '142',
      courseId: 'calculus',
      course: {} as any,
      title: 'Partial Fractions',
      content: 'Find ∫(1/(x² - 1))dx',
      solution: '(1/2)ln|(x-1)/(x+1)| + C',
      difficulty: 'hard',
      topics: ['Integration'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '143',
      courseId: 'calculus',
      course: {} as any,
      title: 'Taylor Series',
      content: 'Find the first 3 terms of the Taylor series for e^x at x = 0',
      solution: '1 + x + x²/2',
      difficulty: 'hard',
      topics: ['Series'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '144',
      courseId: 'calculus',
      course: {} as any,
      title: 'Convergence Test',
      content: 'Does the series Σ(1/n²) converge? Enter 1 for yes, 0 for no.',
      solution: '1',
      difficulty: 'hard',
      topics: ['Series'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '145',
      courseId: 'calculus',
      course: {} as any,
      title: 'Multiple Integration',
      content: 'Find ∫∫(x + y)dxdy over the rectangle [0,1] × [0,2]',
      solution: '2',
      difficulty: 'hard',
      topics: ['Multivariable'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '146',
      courseId: 'calculus',
      course: {} as any,
      title: 'Partial Derivatives',
      content: 'Find ∂f/∂x for f(x,y) = x²y + xy²',
      solution: '2xy + y²',
      difficulty: 'hard',
      topics: ['Multivariable'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '147',
      courseId: 'calculus',
      course: {} as any,
      title: 'Optimization',
      content: 'Find the maximum value of f(x) = -x² + 4x + 1',
      solution: '5',
      difficulty: 'hard',
      topics: ['Applications'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '148',
      courseId: 'calculus',
      course: {} as any,
      title: 'Differential Equations',
      content: 'Solve dy/dx = 2x with y(0) = 1',
      solution: 'x² + 1',
      difficulty: 'hard',
      topics: ['Differential Equations'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '149',
      courseId: 'calculus',
      course: {} as any,
      title: 'Vector Calculus',
      content: 'Find ∇f for f(x,y) = x² + y²',
      solution: '<2x, 2y>',
      difficulty: 'hard',
      topics: ['Multivariable'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '150',
      courseId: 'calculus',
      course: {} as any,
      title: 'Line Integral',
      content: 'Find ∫(x + y)ds along the line from (0,0) to (1,1)',
      solution: '√2',
      difficulty: 'hard',
      topics: ['Multivariable'],
      source: 'Calculus Final Exam',
      year: 2023,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]
} 